name: MARP Presentation Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & Deploy to Main Branch
      env: 
        MARP_ARGS: "--engine ./marpengine.js --input-dir ./source --output ./output"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PUBLISH_TO_BRANCH: published
        BASE_URL: https://blog.stanleysolutionsnw.com
      uses: ralexander-phi/marp-action@master
      
